# Conda environment for Gammapy version 0.14
# Install:    conda env create -f gammapy-0.14-environment.yml
# Activate:   conda activate gammapy-0.14
# Deactivate: conda deactivate

name: gammapy-0.14

channels:
  - conda-forge
  - sherpa

dependencies:
  - gammapy=0.14
  - python=3.7.0
  - ipython=7.8
  - jupyter=1.0
  - jupyterlab=1.1
  - pyyaml=5.1
  - click=7.0
  - numpy=1.17
  - scipy=1.3
  - pandas=0.25
  - matplotlib=3.1
  - astropy=3.2
  - regions=0.4
  - reproject=0.5
  - uncertainties=3.1
  - iminuit=1.3
  - sherpa=4.11
  - healpy=1.12
  - naima=0.8
  - jsonschema=3.0
  - emcee=2.2
  - corner=2.0
  - parfive=1.0
