# Conda environment for Gammapy version 0.13
# Install:    conda env create -f gammapy-0.13-environment.yml
# Activate:   conda activate gammapy-0.13
# Deactivate: conda deactivate

name: gammapy-0.13

channels:
  - conda-forge
  - sherpa

dependencies:
  - gammapy=0.13
  - python=3.7
  - ipython=7.5
  - jupyter=1.0
  - jupyterlab=0.35
  - pyyaml=5.1
  - click=7.0
  - numpy=1.16
  - scipy=1.3
  - pandas=0.24
  - matplotlib=3.1
  - astropy=3.1
  - regions=0.4
  - reproject=0.4
  - uncertainties=3.1
  - iminuit=1.3
  - sherpa=4.11
  - healpy=1.12
  - naima=0.8
