# Conda environment for Gammapy version 0.9
# Install:    conda env create -f gammapy-0.9-environment.yml
# Activate:   conda activate gammapy-0.9
# Deactivate: conda deactivate

name: gammapy-0.9

channels:
  - conda-forge
  - sherpa

dependencies:
  - gammapy=0.9
  - python=3.6
  - ipython=7.1
  - jupyter=1.0
  - jupyterlab=0.35
  - pyyaml=3.13
  - click=7.0
  - numpy=1.15
  - scipy=1.1
  - pandas=0.23
  - matplotlib>=2,<3
  - astropy=3.0
  - regions=0.3
  - reproject=0.4
  - uncertainties=3.0
  - iminuit=1.3
  - sherpa=4.10
  - healpy=1.11
  - naima=0.8
