# Conda environment for Gammapy version 0.15
# Install:    conda env create -f gammapy-0.15-environment.yml
# Activate:   conda activate gammapy-0.15
# Deactivate: conda deactivate

name: gammapy-0.15

channels:
  - conda-forge
  - sherpa

dependencies:
  - gammapy=0.15
  - python=3.7.0
  - ipython=7.10
  # Cython isn't really needed when installing binaries,
  # but it is convenient for users that build from source
  - cython
  - jupyter
  - jupyterlab=1.2
  - pyyaml=5.2
  - click=7.0
  - numpy=1.17
  - scipy=1.3
  - pandas=0.25
  - matplotlib=3.1
  - astropy=3.2
  - regions=0.4
  - iminuit=1.3
  - sherpa=4.11
  - healpy=1.12
  # - naima=0.9
  - pydantic=1.2
  - emcee=3.0
  - corner=2.0
  - parfive=1.0
  - pip
  # temp solution until https://github.com/conda-forge/naima-feedstock/pull/10 is merged
  - pip:
    - naima
